name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Angular app
        run: npm run build -- --configuration=production --output-path=dist/frontend
        working-directory: ./frontend

      - name: Configure Git
        run: |
          git config --global user.email "dev.arammousa@gmail.com"
          git config --global user.name "GIS-Aram"  

      - name: List build output (for debugging)
        run: ls -alh dist/frontend/browser
        working-directory: ./frontend

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/frontend/browser --no-silent
        working-directory: ./frontend
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
